name = "cf-ai-supportbot"
main = "workers/api.ts"
compatibility_date = "2024-10-01"

[env.production]
name = "cf-ai-supportbot"

[env.staging]
name = "cf-ai-supportbot-staging"

# AI Model binding
[ai]
binding = "AI"

# Durable Objects
[[durable_objects.bindings]]
name = "MEMORY_DO"
class_name = "MemoryDurableObject"
script_name = "cf-ai-supportbot"

# KV Storage for caching
[[kv_namespaces]]
binding = "CHAT_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 Storage for archives
[[r2_buckets]]
binding = "ARCHIVE_R2"
bucket_name = "cf-ai-supportbot-archives"
preview_bucket_name = "cf-ai-supportbot-archives-preview"

# Workflows
[workflows]
binding = "WORKFLOWS"

# Environment variables
[vars]
ENVIRONMENT = "development"
MAX_TOKENS = "4096"
RATE_LIMIT_PER_MINUTE = "60"
SESSION_TTL_HOURS = "24"

# Secrets (set via wrangler secret put)
# OPENAI_API_KEY = "your-openai-api-key"
# KNOWLEDGE_BASE_API_KEY = "your-kb-api-key"
# TICKETING_API_KEY = "your-ticketing-api-key"